version: '2'
services:
    web:
        build: .
        restart: always
        ports:
         - '80:80'
        volumes:
         - ./app:/whiskey-blog/app
        depends_on:
         - db
    db:
        build: ./db
        restart: always
