version: '2'
services:
    web:
        build: .
        ports:
         - '80:80'
        volumes:
         - ./uploads:/whiskey-blog/app/static/uploads
        depends_on:
         - db
    db:
        build: ./db
