version: '2'
services:
    web:
        build: .
        restart: always
        ports:
         - '80:80'
        volumes:
         - ./uploads:/whiskey-blog/app/static/uploads
        depends_on:
         - db
    db:
        build: ./db
        restart: always
        volumes:
         - ./db/var/lib/postgresql:/var/lib/postgresql
         - ./db/var/log/postgresql:/var/log/postgresql
